<?php
namespace App\Controller;
use App\Entity\Post;
use App\Entity\File;
use App\Form\PostType;
use App\Repository\PostRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\UERepository;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\Security\Http\Attribute\IsGranted;
/*
    This is the CRUD controller for the Post Entity generated by Symfony Maker Bundle. It was altered to fit the needs of the application. In special the returns.
    

*/

#[Route('/post')]
final class PostController extends AbstractController{
    // Affiche la liste de tous les posts
    #[IsGranted('ROLE_ADMIN')]
    #[Route(name: 'app_post_index', methods: ['GET'])]
    public function index(PostRepository $postRepository): Response
    {   
        return $this->render('post/index.html.twig', [
            'posts' => $postRepository->findAll(),
        ]);
    }
    /*
    *   This is the API responsible for handling the creation of a new post.
    *   It also handles the file upload and stores the file path in the database. Only one file per post is allowed. That's a possible improvement.
    *   With GET method, it returns the form to be displayed in the modal.
    *   With POST method, it handles the form submission and file upload.
    *   User has to be logged in in order for the route to properly work. User is redirected to the login page if not logged in.
    *
    */
    #[IsGranted('ROLE_TEACHER')]
    #[Route('/new', name: 'app_post_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UERepository $ueRepository, SluggerInterface $slugger): Response
    {   
        // On recupere l'utilisateur connecté ou on le redirige vers la page de login
        $user = $this->getUser();
        if (!$user) {
            return $this->redirectToRoute('app_login');
        }
        // On recupere ue_id dans le parametre de la requete
        $ue_id = $request->query->get('ue_id');
        $ue  = $ueRepository->find($ue_id);
        if (!$ue) {
            throw $this->createNotFoundException('UE not found');
        }

        // On cree l'entité POST et initialise ses attributs
        $post = new Post();
        $post->setUserId($user);
        $post->setUeId($ue);
        $post->setDate(new \DateTimeImmutable());

        // Creation et traitement du formulaire Symfony
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // On recupere le fichier uploadé
            $uploadedFile = $form->get('file_path')->getData();
            if ($uploadedFile) {
                // On genere le nom de fichier
                $filename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($filename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$uploadedFile->guessExtension();
                try
                {
                    // On deplace le fichier dans le repertoire de stockage
                    $uploadedFile->move(
                        $this->getParameter('uploads_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // Handle exception 
                }
                // On cree l'entité File et on l'associe au post
                $file = new File();
                $file->setFilePath($newFilename);
                $post->addFile($file);
                $entityManager->persist($file);
            }
            
            $entityManager->persist($post);
            $entityManager->flush();
            return $this->json([
                'success' => true,
                'message' => 'Post created successfully'
            ]);
        }

        // On retourne le formulaire à afficher dans le modal
        return $this->json([
            'success' => true,
            'form' => $this->renderView('post/_form.html.twig', [
                'post' => $post,
                'form' => $form->createView(),
            ])
        ]);
    }
    /*
    *
    *   This is the API responsible for handling the editing of a post.
    *   It also handles the file upload and stores the file path in the database, in case the user wants to change the file.
    *   With GET method, it returns the form to be displayed in the modal.
    *   With POST method, it handles the form submission and file upload.
    *   It expects a Post id int the GET request. It uses Symfony's ParamConverter to automatically convert the id to a Post entity.
    */ 
    #[IsGranted('ROLE_TEACHER')]
    #[Route('/{id}/edit', name: 'app_post_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Post $post, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        //handling of the form submission and file upload.
        if ($form->isSubmitted() && $form->isValid()) {
            // On recupere le fichier uploadé
            $uploadedFile = $form->get('file_path')->getData();
            if ($uploadedFile) {
                // On supprime les anciens fichiers liés au post
                foreach ($post->getFiles() as $existingFile) {    
                    $oldFilePath = $this->getParameter('uploads_directory').'/'.$existingFile->getFilePath();
                    if (file_exists($oldFilePath)) {
                        unlink($oldFilePath);
                    }
                    $post->removeFile($existingFile);
                    $entityManager->remove($existingFile);
                }
                
                // On genere et deplace le nouveau fichier
                $filename = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($filename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$uploadedFile->guessExtension();

                try {
                    $uploadedFile->move(
                        $this->getParameter('uploads_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // Handle upload exception if needed
                }

                // On crée une nouvelle entité File
                $file = new File();
                $file->setFilePath($newFilename);
                $post->addFile($file);
                $entityManager->persist($file);
            }

            // On le met à jour
            $entityManager->flush();

            return $this->json([
                'success' => true,
                'message' => 'Post updated successfully'
            ]);
        }

        // Return of the form html to be displayed in the modal.
        return $this->json([
            'success' => true,
            'form' => $this->renderView('post/_form.html.twig', [
                'post' => $post,
                'form' => $form->createView(),
            ])
        ]);
    }

    /*
    *   This is the API responsible for handling the deletion of a post. 
    */
    #[IsGranted('ROLE_TEACHER')]
    #[Route('/{id}', name: 'app_post_delete', methods: ['POST'])]
    public function delete(Request $request, Post $post, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($post);
            $entityManager->flush();

            return $this->json(['success' => true]);

        }

        return $this->json(['success' => false], 400);   
    }
    /*
    *   This is the API responsible for handling the file download.
    *   It expects a filename in the URL and returns the file as a response.
    */
    #[IsGranted('ROLE_USER')]
    #[Route('/download/{filename}', name: 'post_download_file', methods: ['GET'])]
    public function downloadFile(string $filename): Response
    {
        // On crée le chemin vers le fichier
        $uploadsDir = $this->getParameter('uploads_directory');
        $filePath = $uploadsDir . '/' . $filename;
        
        // On verifie si le fichier existe
        if (!file_exists($filePath)) {
            throw $this->createNotFoundException('File not found.');
        }

        // On verifie le type et renvoie le fichier
        $mimeType = mime_content_type($filePath);
        $originalFilename = pathinfo($filename, PATHINFO_BASENAME);

        return $this->file($filePath, $originalFilename, ResponseHeaderBag::DISPOSITION_ATTACHMENT, [
            'Content-Type' => $mimeType,
        ]);
    }
}

