<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

use App\Entity\User;
use App\Form\UserManagementType;
/*
*   This is the controller responsible for handling the user management page. The user can change its password, name and surname. 
 */

final class UserManagementController extends AbstractController{
    #[Route('/user/management/{id}', name: 'app_user_management')]
    public function index(User $user, Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $userPasswordHasher): Response
    {   
        // UserManagementType is a form that allows the user to change its password, name and surname. It is generated by Symfony Maker Bundle.
        $form = $this->createForm(UserManagementType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $plainPassword = $form->get('plainPassword')->getData();
            if ($plainPassword) {
                $user->setPassword($userPasswordHasher->hashPassword($user, $plainPassword));
            } 
           
            $entityManager->flush();

            return $this->redirectToRoute('app_user_management', ['id' => $user->getId()], Response::HTTP_SEE_OTHER);
            
        }
        
        return $this->render('user_management/index.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }
}
